[profile.default]
src = "src"
out = "out"
libs = ["lib"]

optimizer = true
optimizer_runs = 100_000


[rpc_endpoints]
etherlink="https://node.mainnet.etherlink.com"

[etherscan]
etherlink={ key = "NO_KEY", chain = 42793, url= "https://explorer.etherlink.com/api/" }
